const data=JSON.parse(localStorage.getItem("novaTrackData")||'{"goals":[],"habits":[],"sessions":[],"timeline":[]}');
const state={view:"dashboard",seconds:1500,running:false,timer:null,cloudUser:null};
function save(){localStorage.setItem("novaTrackData",JSON.stringify(data))}
function today(){return new Date().toISOString().slice(0,10)}
function timeNow(){return new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}
function esc(v){return String(v).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
function formatTime(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function localLog(text){data.timeline.push({date:today(),time:timeNow(),text:text,type:"activity",metadata:{}});save()}
async function log(text){if(state.cloudUser){await cloudInsert("timeline_events",{date:today(),time:timeNow(),type:"activity",text:text,metadata:{}});return}localLog(text)}
function focusMinutes(date){date=date||today();return data.sessions.filter(function(s){return s.date===date&&s.status!=="cancelled"}).reduce(function(a,s){return a+(s.minutes||0)},0)}
function completedGoals(){return data.goals.filter(function(g){return g.done}).length}
function completedHabitsToday(){return data.habits.filter(function(h){return h.last===today()}).length}
function productivityScore(){var f=Math.min(focusMinutes(),120)/120*50,g=data.goals.length?completedGoals()/data.goals.length*30:0,h=data.habits.length?completedHabitsToday()/data.habits.length*20:0;return Math.round(f+g+h)}
function dashboard(){var focus=focusMinutes(),done=completedGoals(),streak=Math.max.apply(null,[0].concat(data.habits.map(function(h){return h.streak||0}))),score=productivityScore(),entries=data.timeline.filter(function(x){return x.date===today()}).slice(-8).reverse();var timeline=entries.map(function(x){return "<div>"+esc(x.time)+" — "+esc(x.text)+"</div>"}).join("")||"No activity recorded yet.";return "<div class=\"grid\"><div class=\"card\"><div class=\"metric-label\">FOCUS TODAY</div><div class=\"metric\">"+Math.floor(focus/60)+"h "+String(focus%60).padStart(2,"0")+"m</div><span class=\"muted\">"+(focus?"Focus time recorded":"Start a focus session")+"</span></div><div class=\"card\"><div class=\"metric-label\">GOALS</div><div class=\"metric\">"+done+" / "+data.goals.length+"</div><span class=\"muted\">Completed outcomes</span></div><div class=\"card\"><div class=\"metric-label\">HABIT STREAK</div><div class=\"metric\">"+streak+" days</div><span class=\"muted\">Best current streak</span></div><div class=\"card\"><div class=\"metric-label\">PRODUCTIVITY</div><div class=\"metric\">"+score+"/100</div><span class=\"muted\">V1 daily score</span></div><div class=\"card wide\"><h2 class=\"section-title\">Today's timeline</h2><div class=\"empty\">"+timeline+"</div></div><div class=\"card wide\"><h2 class=\"section-title\">Daily progress</h2><p class=\"muted\">Focus 50% · Goals 30% · Habits 20%</p><div class=\"bar\"><span style=\"width:"+score+"%\"></span></div><p class=\"muted\">"+score+"% productivity score</p></div></div>"}
function goals(){var rows=data.goals.map(function(g,i){return "<div class=\"list-row\"><span>"+(g.done?"✓ ":"")+esc(g.title)+"</span><span><button class=\"btn secondary\" data-goal=\""+i+"\">"+(g.done?"Undo":"Done")+"</button> <button class=\"btn secondary\" data-delete-goal=\""+i+"\">Delete</button></span></div>"}).join("")||"<div class=\"empty\">No goals yet. Add your first goal.</div>";return "<div class=\"card\"><div class=\"cards-title\"><div><h2 class=\"section-title\">Goals</h2><span class=\"muted\">Create and track outcomes that matter.</span></div><button class=\"btn\" id=\"add-goal\">Add goal</button></div><div class=\"list\">"+rows+"</div></div>"}
function habits(){var rows=data.habits.map(function(h,i){return "<div class=\"list-row\"><span>"+esc(h.title)+" <small class=\"muted\">("+(h.streak||0)+" day streak)</small></span><span><button class=\"btn secondary\" data-habit=\""+i+"\">Complete today</button> <button class=\"btn secondary\" data-delete-habit=\""+i+"\">Delete</button></span></div>"}).join("")||"<div class=\"empty\">No habits yet. Add your first habit.</div>";return "<div class=\"card\"><div class=\"cards-title\"><div><h2 class=\"section-title\">Habits</h2><span class=\"muted\">Build consistency through repeatable actions.</span></div><button class=\"btn\" id=\"add-habit\">Add habit</button></div><div class=\"list\">"+rows+"</div></div>"}
function analytics(){var total=data.sessions.reduce(function(a,s){return a+(s.minutes||0)},0),avg=data.sessions.length?Math.round(total/data.sessions.length):0;return "<div class=\"grid\"><div class=\"card\"><div class=\"metric-label\">TODAY'S SCORE</div><div class=\"metric\">"+productivityScore()+"/100</div></div><div class=\"card\"><div class=\"metric-label\">TOTAL FOCUS</div><div class=\"metric\">"+total+"m</div></div><div class=\"card\"><div class=\"metric-label\">SESSIONS</div><div class=\"metric\">"+data.sessions.length+"</div></div><div class=\"card\"><div class=\"metric-label\">AVG SESSION</div><div class=\"metric\">"+avg+"m</div></div><div class=\"card wide\"><h2 class=\"section-title\">Cloud status</h2><div class=\"empty\">"+(state.cloudUser?"Signed in as "+esc(state.cloudUser.email):"Using local browser storage until a cloud account is connected.")+"</div></div></div>"}
function achievements(){var focus=data.sessions.reduce(function(a,s){return a+(s.minutes||0)},0),best=Math.max.apply(null,[0].concat(data.habits.map(function(h){return h.streak||0}))),items=[["First Focus","Complete your first focus session",data.sessions.length>0],["Focused Hour","Accumulate 60 focus minutes",focus>=60],["Deep Worker","Accumulate 300 focus minutes",focus>=300],["Goal Setter","Complete your first goal",completedGoals()>=1],["Goal Crusher","Complete 5 goals",completedGoals()>=5],["Consistency","Reach a 3-day habit streak",best>=3],["Seven Strong","Reach a 7-day habit streak",best>=7],["High Performer","Reach an 80/100 daily score",productivityScore()>=80]];return "<div class=\"card\"><h2 class=\"section-title\">Achievements</h2><div class=\"list\">"+items.map(function(x){return "<div class=\"list-row\"><span>"+(x[2]?"✓":"○")+" <strong>"+x[0]+"</strong><br><small class=\"muted\">"+x[1]+"</small></span><span class=\"pill\">"+(x[2]?"Unlocked":"Locked")+"</span></div>"}).join("")+"</div></div>"}
function settings(){return "<div class=\"card\"><h2 class=\"section-title\">Settings & privacy</h2><p class=\"muted\">"+(state.cloudUser?"Cloud account: "+esc(state.cloudUser.email):"V1 data is stored locally in this browser.")+"</p>"+(state.cloudUser?"<div class=\"profile-grid\"><label>Display name<input id=\"profile-name\" placeholder=\"Your name\"></label><label>Timezone<input id=\"profile-timezone\" placeholder=\"Africa/Lagos\"></label></div><button class=\"btn\" id=\"save-profile\">Save profile</button>":"<p class=\"muted\">Sign in to save a cloud profile.</p>")+"<div class=\"auth-actions\"><button class=\"btn secondary\" id=\"export-data\">Export my data</button><button class=\"btn secondary\" id=\"clear-local\">Clear local data</button>"+(state.cloudUser?"<button class=\"btn secondary\" id=\"delete-cloud\">Delete cloud data</button>":"")+"</div><p class=\"muted\">Deleting cloud data permanently removes your NOVA TRACK records from the connected account.</p></div>" }
var views={dashboard:dashboard,goals:goals,habits:habits,focus:function(){return "<div class=\"card timer\"><div class=\"metric-label\">FOCUS SESSION</div><div class=\"timer-value\" id=\"timer\">"+formatTime(state.seconds)+"</div><button class=\"btn\" id=\"timer-btn\">"+(state.running?"Pause":"Start focus")+"</button> <button class=\"btn secondary\" id=\"reset-btn\">Reset</button></div>"},analytics:analytics,achievements:achievements,settings:settings};
function render(){document.getElementById("view").innerHTML=views[state.view]();document.getElementById("page-title").textContent=state.view.charAt(0).toUpperCase()+state.view.slice(1);document.querySelectorAll(".nav-item").forEach(function(b){b.classList.toggle("active",b.dataset.view===state.view)});bindView()}
function bindView(){
document.getElementById("add-goal")?.addEventListener("click",async function(){var title=prompt("Goal name:");if(title&&title.trim()){var t=title.trim(),g={title:t,done:false};if(state.cloudUser){var row=await cloudInsert("goals",g);g.id=row.id}data.goals.push(g);await log("Created goal: "+t);save();render()}});
document.querySelectorAll("[data-goal]").forEach(function(b){b.onclick=async function(){var g=data.goals[+b.dataset.goal];g.done=!g.done;g.completedAt=g.done?new Date().toISOString():null;if(state.cloudUser)await cloudUpdate("goals",g.id,{done:g.done,completed_at:g.completedAt});await log((g.done?"Completed goal: ":"Reopened goal: ")+g.title);save();render()}});
document.querySelectorAll("[data-delete-goal]").forEach(function(b){b.onclick=async function(){var g=data.goals.splice(+b.dataset.deleteGoal,1)[0];if(state.cloudUser&&g.id)await cloudDelete("goals",g.id);await log("Deleted goal: "+g.title);render()}});
document.getElementById("add-habit")?.addEventListener("click",async function(){var title=prompt("Habit name:");if(title&&title.trim()){var t=title.trim(),h={title:t,streak:0,last:null};if(state.cloudUser){var row=await cloudInsert("habits",{title:t,streak:0,last_completed_date:null});h.id=row.id}data.habits.push(h);await log("Created habit: "+t);save();render()}});
document.querySelectorAll("[data-habit]").forEach(function(b){b.onclick=async function(){var h=data.habits[+b.dataset.habit];if(h.last!==today()){h.streak=(h.streak||0)+1;h.last=today();if(state.cloudUser)await cloudUpdate("habits",h.id,{streak:h.streak,last_completed_date:h.last});await log("Completed habit: "+h.title);render()}else alert("This habit is already completed today.")}});
document.querySelectorAll("[data-delete-habit]").forEach(function(b){b.onclick=async function(){var h=data.habits.splice(+b.dataset.deleteHabit,1)[0];if(state.cloudUser&&h.id)await cloudDelete("habits",h.id);await log("Deleted habit: "+h.title);render()}});
if(state.view==="focus")bindTimer();
document.getElementById("save-profile")?.addEventListener("click",async function(){try{var name=document.getElementById("profile-name").value.trim(),tz=document.getElementById("profile-timezone").value.trim()||Intl.DateTimeFormat().resolvedOptions().timeZone;await cloudUpdateProfile({display_name:name||null,timezone:tz});alert("Profile saved.");render();await loadCloudIntoApp()}catch(e){alert(e.message||"Could not save profile.")}});
if(state.view==="settings"&&state.cloudUser){cloudGetProfile().then(function(p){if(p){var n=document.getElementById("profile-name"),tz=document.getElementById("profile-timezone");if(n)n.value=p.display_name||"";if(tz)tz.value=p.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone}}).catch(function(e){console.error("NOVA TRACK profile:",e)})}
document.getElementById("export-data")?.addEventListener("click",function(){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="nova-track-data-"+today()+".json";a.click();URL.revokeObjectURL(url)});document.getElementById("clear-local")?.addEventListener("click",function(){if(confirm("Clear all NOVA TRACK data stored in this browser? This does not delete cloud data.")){localStorage.removeItem("novaTrackData");location.reload()}});document.getElementById("delete-cloud")?.addEventListener("click",async function(){if(!confirm("Delete ALL cloud data for this account? This cannot be undone."))return;try{await cloudDeleteAll();localStorage.removeItem("novaTrackData");alert("Cloud data deleted.");location.reload()}catch(e){alert(e.message||"Could not delete cloud data.")}})
}
function bindTimer(){var b=document.getElementById("timer-btn"),r=document.getElementById("reset-btn");b.onclick=function(){if(state.running){clearInterval(state.timer);state.running=false;log("Paused focus session");render();return}state.running=true;log("Started focus session");clearInterval(state.timer);state.timer=setInterval(async function(){if(state.seconds>0){state.seconds--;var el=document.getElementById("timer");if(el)el.textContent=formatTime(state.seconds)}else{clearInterval(state.timer);state.running=false;var session={date:today(),minutes:25,status:"completed"};if(state.cloudUser){var row=await cloudInsert("focus_sessions",session);session.id=row.id}data.sessions.push(session);await log("Completed 25-minute focus session");state.seconds=1500;render()}},1000);render()};r.onclick=function(){clearInterval(state.timer);state.running=false;state.seconds=1500;log("Reset focus session");render()}}
async function loadCloudIntoApp(){if(!SUPABASE_READY)return;var user=await getUser();if(!user){state.cloudUser=null;return}state.cloudUser=user;await migrateLocalData(user);var remote=await loadCloudData(user);data.goals=remote.goals;data.habits=remote.habits;data.sessions=remote.sessions;data.timeline=remote.timeline;save();render()}
window.novaRefreshCloud=loadCloudIntoApp;
document.querySelectorAll(".nav-item").forEach(function(b){b.addEventListener("click",function(){state.view=b.dataset.view;render()})});
document.getElementById("today").textContent=new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date());
render();loadCloudIntoApp().catch(function(e){console.error("NOVA TRACK cloud load:",e)});