const saved=JSON.parse(localStorage.getItem("novaTrackData")||"{\"goals\":[],\"habits\":[],\"sessions\":[],\"timeline\":[]}");\nconst state={view:"dashboard",seconds:25*60,running:false,timer:null};\nconst data=saved;\nfunction save(){localStorage.setItem("novaTrackData",JSON.stringify(data))}\nfunction today(){return new Date().toISOString().slice(0,10)}
const views={
dashboard:()=>`<div class="grid"><div class="card"><div class="metric-label">FOCUS TODAY</div><div class="metric">0h 00m</div><span class="muted">Start a focus session</span></div><div class="card"><div class="metric-label">GOALS</div><div class="metric">0 / 0</div><span class="muted">No active goals yet</span></div><div class="card"><div class="metric-label">HABIT STREAK</div><div class="metric">0 days</div><span class="muted">Build your first streak</span></div><div class="card"><div class="metric-label">PRODUCTIVITY</div><div class="metric">—</div><span class="muted">Not enough data</span></div><div class="card wide"><h2 class="section-title">Today's timeline</h2><div class="empty">No activity recorded yet.<br/>Your timeline will appear here as NOVA TRACK collects activity.</div></div><div class="card wide"><h2 class="section-title">Daily progress</h2><p class="muted">Complete goals and focus sessions to build today's progress.</p><div class="bar"><span style="width:0%"></span></div></div></div>`,
goals:()=>panel("Goals","Create and track outcomes that matter.","No goals yet. Your first V1 goal system will live here."),
habits:()=>panel("Habits","Build consistency through repeatable actions.","No habits yet. Add your first habit to begin a streak."),
analytics:()=>panel("Analytics","Understand where your time and effort are going.","Analytics will populate after activity and focus data exists."),
achievements:()=>panel("Achievements","Milestones earned through consistent progress.","No achievements unlocked yet."),
settings:()=>panel("Settings","Control your NOVA TRACK experience.","V1 settings will be added here as the data layer grows."),
focus:()=>`<div class="card timer"><div class="metric-label">FOCUS SESSION</div><div class="timer-value" id="timer">${formatTime(state.seconds)}</div><button class="btn" id="timer-btn">${state.running?"Pause":"Start focus"}</button> <button class="btn secondary" id="reset-btn">Reset</button></div>`
};
function panel(title,sub,empty){return `<div class="card"><div class="cards-title"><div><h2 class="section-title">${title}</h2><span class="muted">${sub}</span></div><span class="pill">V1</span></div><div class="empty">${empty}</div></div>`}
function formatTime(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function render(){document.getElementById("view").innerHTML=views[state.view]();document.getElementById("page-title").textContent=state.view[0].toUpperCase()+state.view.slice(1);document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));if(state.view==="focus")bindTimer()}
function bindTimer(){const b=document.getElementById("timer-btn"),r=document.getElementById("reset-btn");b.onclick=()=>{state.running=!state.running;if(state.running)state.timer=setInterval(()=>{if(state.seconds>0)state.seconds--;else{state.running=false;clearInterval(state.timer)}render()},1000);else clearInterval(state.timer);render()};r.onclick=()=>{state.running=false;clearInterval(state.timer);state.seconds=25*60;render()}}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{state.view=b.dataset.view;render()}));document.getElementById("today").textContent=new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date());render();